# Generated by Django 6.1.1 on 2026-09-20 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('blood_group', models.CharField(choices=[('A_POSITIVE', 'A+'), ('A_NEGATIVE', 'A-'), ('B_POSITIVE', 'B+'), ('B_NEGATIVE', 'B-'), ('AB_POSITIVE', 'AB+'), ('AB_NEGATIVE', 'AB-'), ('O_POSITIVE', 'O+'), ('O_NEGATIVE', 'O-')], max_length=20)),
                ('component_type', models.CharField(choices=[('RBC', 'Red Blood Cells'), ('PLASMA', 'Plasma'), ('PLATELETS', 'Platelets'), ('WHOLE_BLOOD', 'Whole Blood')], max_length=30)),
                ('collection_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField(default=0)),
                ('reserved_quantity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('USABLE', 'Usable'), ('QUARANTINED', 'Quarantined'), ('EXPIRED', 'Expired'), ('RESERVED', 'Reserved')], default='USABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='facilities.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A_POSITIVE', 'A+'), ('A_NEGATIVE', 'A-'), ('B_POSITIVE', 'B+'), ('B_NEGATIVE', 'B-'), ('AB_POSITIVE', 'AB+'), ('AB_NEGATIVE', 'AB-'), ('O_POSITIVE', 'O+'), ('O_NEGATIVE', 'O-')], max_length=20)),
                ('component_type', models.CharField(choices=[('RBC', 'Red Blood Cells'), ('PLASMA', 'Plasma'), ('PLATELETS', 'Platelets'), ('WHOLE_BLOOD', 'Whole Blood')], max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='facilities.facility')),
            ],
        ),
        migrations.CreateModel(
            name='BloodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A_POSITIVE', 'A+'), ('A_NEGATIVE', 'A-'), ('B_POSITIVE', 'B+'), ('B_NEGATIVE', 'B-'), ('AB_POSITIVE', 'AB+'), ('AB_NEGATIVE', 'AB-'), ('O_POSITIVE', 'O+'), ('O_NEGATIVE', 'O-')], max_length=20)),
                ('component_type', models.CharField(choices=[('RBC', 'Red Blood Cells'), ('PLASMA', 'Plasma'), ('PLATELETS', 'Platelets'), ('WHOLE_BLOOD', 'Whole Blood')], max_length=30)),
                ('available_units', models.IntegerField(default=0)),
                ('reserved_units', models.IntegerField(default=0)),
                ('quarantined_units', models.IntegerField(default=0)),
                ('near_expiry_units', models.IntegerField(default=0)),
                ('incoming_units', models.IntegerField(default=0)),
                ('expected_expiry_units', models.IntegerField(default=0)),
                ('safety_stock_target', models.IntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_summaries', to='facilities.facility')),
            ],
            options={
                'unique_together': {('facility', 'blood_group', 'component_type')},
            },
        ),
    ]
