# Generated by Django 6.1.1 on 2026-09-20 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=255)),
                ('location', models.CharField(default='Main Blood Center', max_length=255)),
                ('target_blood_groups', models.CharField(default='ALL', max_length=255)),
                ('target_units', models.IntegerField(default=50)),
                ('collected_units', models.IntegerField(default=0)),
                ('campaign_date', models.DateField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('created_by', models.CharField(default='SYSTEM', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='facilities.facility')),
            ],
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A_POSITIVE', 'A+'), ('A_NEGATIVE', 'A-'), ('B_POSITIVE', 'B+'), ('B_NEGATIVE', 'B-'), ('AB_POSITIVE', 'AB+'), ('AB_NEGATIVE', 'AB-'), ('O_POSITIVE', 'O+'), ('O_NEGATIVE', 'O-')], max_length=20)),
                ('component_type', models.CharField(choices=[('RBC', 'Red Blood Cells'), ('PLASMA', 'Plasma'), ('PLATELETS', 'Platelets'), ('WHOLE_BLOOD', 'Whole Blood')], max_length=30)),
                ('units_used', models.IntegerField(default=1)),
                ('usage_date', models.DateField()),
                ('recorded_by', models.CharField(default='SYSTEM', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='facilities.facility')),
            ],
        ),
    ]
