# Generated by Django 6.1.1 on 2026-09-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('BLOOD_BANK', 'Blood Bank'), ('LOGISTICS', 'Logistics Center'), ('REGIONAL_ADMIN', 'Regional Administration')], default='HOSPITAL', max_length=50)),
                ('region', models.CharField(default='Central', max_length=100)),
                ('city', models.CharField(default='Metropolis', max_length=100)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('population_served', models.IntegerField(default=0)),
                ('bed_capacity', models.IntegerField(default=0)),
                ('icu_beds', models.IntegerField(default=0)),
                ('emergency_capacity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
