# Generated by Django 6.1.1 on 2026-09-21 17:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_id', models.CharField(db_index=True, help_text='Deterministic business notification ID ensuring idempotency across retries.', max_length=150, unique=True)),
                ('event_type', models.CharField(choices=[('transfer_pending_approval', 'Transfer Pending Approval'), ('transfer_approved', 'Transfer Approved'), ('transfer_in_transit', 'Transfer In Transit'), ('transfer_received', 'Transfer Received'), ('low_stock_warning', 'Low Stock Warning'), ('demand_estimate_ready', 'Demand Estimate Ready'), ('notification_test', 'Notification Test')], max_length=50)),
                ('recipient_role', models.CharField(max_length=50)),
                ('recipient_reference', models.CharField(blank=True, default='', max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Local Dispatch'), ('submitted', 'Submitted to Make.com Webhook Queue'), ('sent', 'Accepted by Notification Provider'), ('demonstration_sent', 'Simulated Demonstration Sent'), ('failed', 'Delivery Failed'), ('duplicate_prevented', 'Duplicate Prevented')], db_index=True, default='pending', max_length=30)),
                ('is_demo', models.BooleanField(default=True)),
                ('payload', models.JSONField(default=dict)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('external_deduplication_detected', models.BooleanField(default=False)),
                ('last_callback_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='notificatio_status_1e9b53_idx')],
            },
        ),
    ]
