# Generated by Django 6.1.1 on 2026-09-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdelivery',
            name='provider_message_id',
            field=models.CharField(blank=True, db_index=True, help_text='External Brevo message ID returned upon API acceptance.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Local Dispatch'), ('submitted', 'Submitted to Email API Queue'), ('sent', 'Accepted by Notification Provider'), ('demonstration_sent', 'Simulated Demonstration Sent'), ('failed', 'Delivery Failed'), ('duplicate_prevented', 'Duplicate Prevented')], db_index=True, default='pending', max_length=30),
        ),
    ]
