# Generated by Django 6.1.1 on 2026-09-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationdelivery_provider_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Local Dispatch'), ('submitted', 'Submitted to Email API Queue'), ('sent', 'Accepted by Notification Provider'), ('delivered', 'Delivered to Recipient'), ('demonstration_sent', 'Simulated Demonstration Sent'), ('failed', 'Delivery Failed'), ('duplicate_prevented', 'Duplicate Prevented')], db_index=True, default='pending', max_length=30),
        ),
    ]
