# Generated by Django 6.1.1 on 2026-09-20 11:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('event_id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('actor', models.CharField(default='SYSTEM', max_length=255)),
                ('role', models.CharField(default='SYSTEM', max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('correlation_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
