# Generated by Django 6.1.1 on 2026-09-20 16:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('facility_id', models.CharField(max_length=100)),
                ('facility_name', models.CharField(default='Unknown Facility', max_length=255)),
                ('alert_type', models.CharField(choices=[('SHORTAGE', 'Critical Shortage'), ('EXPIRY', 'Near Expiry'), ('LOW_STOCK', 'Low Inventory'), ('PENDING_APPROVAL', 'Pending Transfer Approval')], max_length=50)),
                ('severity', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=20, null=True)),
                ('component_type', models.CharField(blank=True, max_length=30, null=True)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
