# Generated by Django 6.1.1 on 2026-09-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_name', models.CharField(max_length=100)),
                ('baseline_demand', models.FloatField(default=1.0)),
                ('modified_demand', models.FloatField(default=1.0)),
                ('risk_summary', models.JSONField(default=dict)),
                ('created_by', models.CharField(default='SYSTEM', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
