# Generated by Django 6.1.1 on 2026-09-20 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=20)),
                ('component_type', models.CharField(max_length=30)),
                ('forecast_date', models.DateField()),
                ('p10', models.FloatField()),
                ('p50', models.FloatField()),
                ('p90', models.FloatField()),
                ('protection_level', models.FloatField(default=0.0)),
                ('model_name', models.CharField(default='XGBoost', max_length=100)),
                ('prediction_interval_type', models.CharField(default='Estimated prediction interval', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='facilities.facility')),
            ],
        ),
    ]
