# Generated by Django 6.1.1 on 2026-09-20 11:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(max_length=20)),
                ('component_type', models.CharField(max_length=30)),
                ('requested_quantity', models.IntegerField(default=1)),
                ('approved_quantity', models.IntegerField(default=1)),
                ('safe_share_quantity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING_APPROVAL', max_length=30)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], default='URGENT', max_length=20)),
                ('requested_by', models.CharField(default='SYSTEM', max_length=255)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('source_deducted', models.BooleanField(default=False)),
                ('destination_added', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='facilities.facility')),
                ('source_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='facilities.facility')),
            ],
        ),
    ]
